spring:
  profiles:
    active: local
  redis:
    host: localhost
    port: 6379
  session:
    timeout: 14400
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session
  mail:
    host: smtp.gmail.com
    port: 587
    username: tpwls2785@gmail.com
    password: qeoayhfnocobftus
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/temp
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/audition?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
mybatis:
  type-aliases-package: com.quantom.audition
server:
  error:
    include-exception: true
    include-stacktrace: always
    include-message: always
    include-binding-errors: always
custom:
  siteName: 오디션 트리
  siteMainUri: https://bangsuyeong.shop:8080/usr/member/login
  logoText: 오디션 트리
  emailFrom: tpwls2785@locahost
  emailFromName: 방수
  genFileDirPath: C:/work/sts-4.8.0.RELEASE-workspace/at-file
  logging:
    dir: log
    level: info
 
 
---

spring:
  profiles: local
server:
  port: 8080

---

spring:
  profiles: production
  servlet:
    multipart:
      location: /tmp
  datasource:
    username: auditionLocal
    password: dheltus123414
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/audition?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
custom:
  genFileDirPath: /opt/tomcat/apache-tomcat-9.0.37/bangsuyeong.shop-file
  logging:
    dir: /tmp/bangsuyeong-resource-log 
    level: info