server:
  port: 8081
  
spring:
  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/temp
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/audition?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
mybatis:
  type-aliases-package: com.quantom.audition
custom:
  logoText: 오디션 트리
 